package com.smartfactory.enums;

public enum QualityCheckType {
    TEMPERATURE,
    PROCESSING_TIME,
    FLOW_RATE,
    YIELD,
    PULP_CONDITION,
    CLEANLINESS,
    FILTRATION_RESULT,
    RECIPE_COMPLIANCE,
    FILL_QUANTITY,
    CAP_STATUS,
    BOTTLE_CONDITION,
    LABEL_STATUS,
    PACKAGE_INTEGRITY,
    BOTTLE_COUNT,
    FINAL_QUANTITY,
    FRUIT_CONDITION,
    SORTING_RESULT,
    REJECTED_QUANTITY,
    BATCH_QUANTITY,
    INCOMING_QUANTITY,
    MANUAL_INSPECTION,
    PARTICLE_QUALITY,
    FINISHED_GOODS_STATE
}
